name: CI

on:
  push:
    branches: [ main, rethink ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,docs]"
    - name: Lint with flake8
      run: flake8
    - name: Type check with mypy
      run: mypy --ignore-missing-imports .
    - name: Test with pytest
      run: pytest --cov=cli_builder tests/
    
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t cli-builder:latest .
    - name: Run tests in Docker
      run: docker run cli-builder:latest 